controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: 'en|nl'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
